spring:
  # Redis配置
  redis:
    # redis服务器地址（默认为localhost）
    host: ${app.redis.host}
    # redis端口（默认为6379）
    port: ${app.redis.port}
    # redis访问密码（默认为空）
    password: ${app.redis.password}
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 20
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 5
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 20
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: 2